// This first few elements was created by me the rest was generated by using Ai Tool (Chatgpt)

const ourWords = [
  {
    word: "beach",
    hint: "A place you relax in",
    funFact:
      "Beaches can be any color based on the rock they’re made from, with white sand often being preferred for its beauty and heat reflection.",
  },
  { word: "booth", hint: "A place to show your products in" },
  {
    word: "fruit",
    hint: "Something Sweet & Natural",
    funFact: "Cucumbers and Tomatoes are actually fruits",
  },
  {
    word: "apple",
    hint: "Something Keeps the doctor Away!",
    funFact:
      "Did you know that the common name for apple comes from the word 'æppel', an Old English word meaning fruit?",
  },
  {
    word: "quack",
    hint: "Sound a duck makes",
    funFact:
      "Ducks’ quacks are famously said to not echo—but that’s actually a myth!",
  },
  {
    word: "plume",
    hint: "Feather or smoke shape",
    funFact: "The word 'plume' comes from the Latin word for feather: 'pluma'.",
  },
  {
    word: "glint",
    hint: "A tiny flash of light",
    funFact:
      "A glint can be from a reflection off a small surface, like a shard of glass.",
  },
  {
    word: "mirth",
    hint: "Joyful laughter",
    funFact: "Mirth used to mean 'peace and rest' in old English.",
  },
  {
    word: "knack",
    hint: "A special talent",
    funFact: "Having a 'knack' originally referred to a trick or contrivance.",
  },
  {
    word: "brood",
    hint: "A group of young animals",
    funFact:
      "Brooding can also mean to think deeply about something troubling.",
  },
  {
    word: "crypt",
    hint: "Underground chamber",
    funFact:
      "Crypts are often found beneath churches and used as burial places.",
  },
  {
    word: "drift",
    hint: "To be carried slowly by air or water",
    funFact: "Snowdrifts can pile up in very large amounts during blizzards.",
  },
  {
    word: "blitz",
    hint: "A sudden, energetic attack or effort",
    funFact:
      "The word 'blitz' comes from the German word for lightning, 'Blitzkrieg'.",
  },
  {
    word: "flock",
    hint: "A group of birds",
    funFact:
      "A group of sheep can also be called a flock, as can people moving together.",
  },
  {
    word: "hatch",
    hint: "A small door or opening",
    funFact: "Hatches are often found in ships or airplanes as access points.",
  },
  {
    word: "cliff",
    hint: "A steep face of rock",
    funFact:
      "Cliffs are often formed by the processes of erosion and weathering.",
  },
  {
    word: "prism",
    hint: "A transparent geometric shape",
    funFact: "Prisms can separate white light into a spectrum of colors.",
  },
  {
    word: "spear",
    hint: "A pole weapon with a pointed end",
    funFact:
      "Spears were one of the earliest tools used by humans for hunting.",
  },
  {
    word: "grain",
    hint: "A small, hard seed",
    funFact: "Grain is a staple food in many cultures around the world.",
  },
  {
    word: "carol",
    hint: "A festive song",
    funFact: "The tradition of singing carols dates back to the Middle Ages.",
  },
  {
    word: "spike",
    hint: "A sharp, pointed object",
    funFact:
      "Spikes are used in various sports such as track and field for grip.",
  },
  {
    word: "lodge",
    hint: "A small house or cabin",
    funFact:
      "The word 'lodge' also refers to a beaver's home, typically made of sticks and mud.",
  },
  {
    word: "trout",
    hint: "A freshwater fish",
    funFact:
      "Trout are closely related to salmon and can often be found in cold streams.",
  },
  {
    word: "swamp",
    hint: "A wetland with trees",
    funFact:
      "Swamps play an important role in filtering water and providing habitat for wildlife.",
  },
  {
    word: "elbow",
    hint: "The joint in the middle of your arm",
    funFact:
      "The 'funny bone' is actually a nerve near your elbow, not a bone!",
  },
  {
    word: "wrist",
    hint: "The joint connecting the hand and forearm",
    funFact: "Your wrist is made up of eight small bones called carpals.",
  },
  {
    word: "frost",
    hint: "Ice crystals formed on a surface",
    funFact:
      "Frost typically forms on clear, cold nights when the temperature drops below freezing.",
  },
  {
    word: "spool",
    hint: "A cylinder around which thread is wound",
    funFact: "Spools can also be used to store electrical cables and wire.",
  },
  {
    word: "gland",
    hint: "An organ that secretes hormones",
    funFact:
      "The pituitary gland is often referred to as the 'master gland' because it controls many other hormone glands in the body.",
  },
  {
    word: "hover",
    hint: "To remain in one place in the air",
    funFact:
      "Hummingbirds are one of the few bird species capable of hovering in place.",
  },
  {
    word: "guild",
    hint: "An association of artisans or merchants",
    funFact:
      "Guilds were important in the Middle Ages for regulating trade and protecting their members' interests.",
  },
  {
    word: "plush",
    hint: "A rich, soft fabric",
    funFact:
      "Plush toys, often called stuffed animals, are commonly made with this material.",
  },
  {
    word: "scrub",
    hint: "A type of small, hardy plant",
    funFact:
      "Scrublands are areas of land with low-growing vegetation, often found in arid regions.",
  },
  {
    word: "briar",
    hint: "A thorny plant or shrub",
    funFact:
      "Briar patches are known for being dense and difficult to navigate through.",
  },
  {
    word: "shelf",
    hint: "A flat surface used for storage",
    funFact:
      "Shelves can be made from wood, metal, or plastic and come in many shapes and sizes.",
  },
  {
    word: "flask",
    hint: "A small container for liquids",
    funFact:
      "Flasks are often used to store alcohol or other beverages on the go.",
  },
  {
    word: "sheen",
    hint: "A soft glow or shine",
    funFact:
      "The sheen on a surface is often the result of polishing or exposure to light.",
  },
  {
    word: "crate",
    hint: "A large shipping container",
    funFact: "Crate expectations? Always prepare for a big haul!",
  },
  {
    word: "frill",
    hint: "An ornamental ruffle or trim",
    funFact: "Frills are like the fashion world’s way of saying ‘I tried.’",
  },
  {
    word: "spade",
    hint: "A tool used for digging",
    funFact:
      "A spade can help you dig, but it can't dig you out of awkward conversations.",
  },
  {
    word: "pouch",
    hint: "A small bag or pocket",
    funFact:
      "Kangaroos use pouches for their babies, while humans use them for snacks.",
  },
  {
    word: "stalk",
    hint: "The main stem of a plant",
    funFact: "Not to be confused with ‘stalking’ someone on social media.",
  },
  {
    word: "chill",
    hint: "A cold sensation",
    funFact:
      "The best advice: ‘Netflix and chill’—especially if it’s cold outside!",
  },
  {
    word: "creek",
    hint: "A small stream",
    funFact:
      "If you’re up a creek without a paddle, you might want to learn how to swim!",
  },
  {
    word: "ledge",
    hint: "A narrow shelf along a wall",
    funFact:
      "Ledges are great for storing things... until your cat decides to knock them off.",
  },
  {
    word: "whisk",
    hint: "A kitchen tool used to mix ingredients",
    funFact:
      "Whisks are for mixing... or for pretending you’re conducting an orchestra in the kitchen.",
  },
  {
    word: "chalk",
    hint: "A soft white rock used for writing",
    funFact: "Chalk: The original touchscreen for blackboards.",
  },
  {
    word: "swirl",
    hint: "A twisting or spiraling pattern",
    funFact: "Ice cream swirl: When two flavors fight, everyone wins.",
  },
  {
    word: "badge",
    hint: "An emblem or mark of achievement",
    funFact:
      "Getting a badge feels great—until you realize it doesn’t get you a free coffee.",
  },
  {
    word: "blurb",
    hint: "A short promotional summary",
    funFact:
      "Blurbs are like teasers for books... because who has time to read the whole thing?",
  },
  {
    word: "pinky",
    hint: "The smallest finger on your hand",
    funFact:
      "The pinky might be small, but it’s the most likely to participate in a promise.",
  },
  {
    word: "grove",
    hint: "A small group of trees",
    funFact: "A grove is where trees hang out... sort of like a tree party.",
  },
  {
    word: "brisk",
    hint: "Quick and energetic",
    funFact:
      "A brisk walk is great exercise... or a great way to avoid awkward conversations.",
  },
  {
    word: "prong",
    hint: "A pointed end of something",
    funFact: "Prongs on a fork are like tiny spears for your salad.",
  },
  {
    word: "chime",
    hint: "A sound made by bells",
    funFact: "Chimes are great for relaxing—until you hear them at 3 AM.",
  },
  {
    word: "perch",
    hint: "A spot for sitting or resting",
    funFact:
      "Birds love to perch... but only on the things you don’t want them to.",
  },
  {
    word: "globe",
    hint: "A spherical map of the world",
    funFact:
      "Spinning a globe is like saying ‘where’s my next vacation?’ and then landing on the ocean.",
  },
  {
    word: "shrug",
    hint: "A gesture of uncertainty",
    funFact:
      "When words fail, just shrug. It’s like the ‘I don’t know’ of body language.",
  },
  {
    word: "plaid",
    hint: "A checkered pattern",
    funFact:
      "Plaid: The official uniform of lumberjacks and hipsters everywhere.",
  },
  {
    word: "beady",
    hint: "Small, round, and shiny",
    funFact:
      "Beady eyes are cute on birds... less so when your boss gives you that look.",
  },
  {
    word: "couch",
    hint: "A comfortable seat for multiple people",
    funFact: "Couches are like quicksand: Once you sit, you may never leave.",
  },
  {
    word: "scoop",
    hint: "A utensil for picking up something",
    funFact:
      "The bigger the scoop, the better the ice cream cone. That’s just science.",
  },
  {
    word: "snoop",
    hint: "To pry or spy into something",
    funFact:
      "Snooping is bad... unless you find cookies, then it’s a public service.",
  },
  {
    word: "peril",
    hint: "Serious danger",
    funFact: "Peril is basically life’s way of saying ‘plot twist!’",
  },
  {
    word: "twist",
    hint: "A sudden change or bend",
    funFact:
      "Plot twists: The reason your favorite TV show keeps you up all night.",
  },
  {
    word: "crisp",
    hint: "Firm and dry texture",
    funFact: "Crisp weather is great... until you forget your jacket.",
  },
  {
    word: "dandy",
    hint: "Excellent or fine",
    funFact: "Everything’s just dandy—until you step on a Lego.",
  },
  {
    word: "flake",
    hint: "A small, thin piece of something",
    funFact: "Snowflakes are unique, just like that excuse for being late.",
  },
  {
    word: "slump",
    hint: "A drop or decline",
    funFact:
      "If you’re in a slump, just remember: even the best cookies crumble sometimes.",
  },
  {
    word: "glare",
    hint: "A strong, harsh light",
    funFact: "The sun’s glare: Great for tanning, terrible for selfies.",
  },
  {
    word: "latch",
    hint: "A fastener for a door or gate",
    funFact:
      "A door latch is great... unless you're trying to sneak snacks at night.",
  },
  {
    word: "gleam",
    hint: "A bright or shining light",
    funFact:
      "Gleaming teeth: What you get from smiling at your dentist’s bad jokes.",
  },
  {
    word: "scout",
    hint: "Someone who explores or searches",
    funFact: "Scouts are great at finding things—unless it’s their car keys.",
  },
  {
    word: "slant",
    hint: "A tilted position or perspective",
    funFact:
      "A slanted view is just a fancy way of saying ‘I’m seeing things differently!’",
  },
  {
    word: "groan",
    hint: "A sound of discomfort or annoyance",
    funFact: "Groaning: What happens when you realize the weekend is over.",
  },
  {
    word: "scram",
    hint: "To leave quickly",
    funFact: "Scram! The universal word for ‘I saw you eating my fries.’",
  },
  {
    word: "pluck",
    hint: "To pull or pick something",
    funFact: "Pluck: What happens when your eyebrows have a mind of their own.",
  },
  {
    word: "glide",
    hint: "To move smoothly",
    funFact:
      "Glide through life like a penguin on ice… unless you trip, then just play it cool.",
  },
  {
    word: "prone",
    hint: "Likely to suffer from or do something",
    funFact:
      "Prone to procrastination? It’s okay, you’ll finish this... eventually.",
  },
  {
    word: "snack",
    hint: "A small amount of food",
    funFact:
      "Snack: The most important meal of the day... according to anyone who’s ever been hungry.",
  },
  {
    word: "fluke",
    hint: "A stroke of luck",
    funFact:
      "Flukes are rare... kind of like finding matching socks on laundry day.",
  },
  {
    word: "perch",
    hint: "A resting spot for birds",
    funFact:
      "Birds perch on branches... because they’re just too fancy for chairs.",
  },
]
